version: '3.9'

services:
  oauth2-proxy:
    image: bitnami/oauth2-proxy:7.4.0
    command:
      - '--provider=' #TODO Fill
      - '--email-domain=' #TODO Fill
      - '--upstream=http://host.docker.internal:8080' # Win\Mac - host.docker.internal.
      - '--http-address=0.0.0.0:4180'
      - '--oidc-issuer-url=' #TODO Fill
      - '--ssl-insecure-skip-verify=true'
      - '--ssl-upstream-insecure-skip-verify=true'
      - '--scope="openid email profile"'
      - '--resource=' #TODO Fill
      - '--redirect-url=http://localhost:4180/oauth2/callback'
      - '--pass-access-token=true'
      - '--set-authorization-header=true'
      - '--pass-authorization-header=true'
      - '--session-store-type=redis'
      - '--redis-connection-url=redis://redis:6379/0'
      - '--client-id=' #TODO Fill
      - '--client-secret=' #TODO Fill
      - '--cookie-secret=' #TODO Fill
    ports:
      - "4180:4180"
    extra_hosts:
      - "host.docker.internal:host-gateway" # TODO Linux only
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    environment:
      - REDIS_AOF_ENABLED=no