apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    orgId: 1
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: GET

  - name: tempo
    type: tempo
    uid: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    jsonData:
      httpHeaderTenant: 'X-Scope-OrgID'
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      tracesToLogs: # mapping traces to logs datasource
        mappedTags: [{ key: 'service.name', value: 'container_name' }]
        datasourceUid: 'loki'
        mapTagNamesEnabled: true
        #spanStartTimeShift: '5s' #shifts grafana timerange forward and can cause empty search result
        spanEndTimeShift: '5s'
        filterByTraceID: true
        filterBySpanID: true # not all spans have logs but link is displayed for both
        lokiSearch: true
      tracesToMetrics:
        datasourceUid: 'prometheus'
        tags: [ { key: 'service.name', value: 'application' } ]
        queries:
          - name: 'Request rate'
            query: 'sum by(uri) (rate(http_server_requests_count{$$__tags}[5m])) '
          - name: 'Request error rate'
            query: 'sum by(uri, outcome) (rate(http_server_requests_count{$$__tags, outcome=~"CLIENT_ERROR|SERVER_ERROR"}[5m])) '
    secureJsonData:
      httpHeaderTenant: 'Organization 1'
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: '$${__value.raw}'
    editable: true