apiVersion: v2
name: Observability All in One
description: A Helm chart for running full observability stack on single Kubernetes cluster
type: application
version: 0.1.0
appVersion: "0.0.1"

dependencies:
  # Logging
  - name: loki
    version: 6.30.0
    repository: https://grafana.github.io/helm-charts
  - name: vector
    version: 0.43.0
    repository: https://helm.vector.dev
  # Metrics
  - name: kube-state-metrics
    version: 5.33.2
    repository: https://prometheus-community.github.io/helm-charts
  - name: prom-label-proxy
    version: 0.12.2
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-node-exporter
    version: 4.46.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: victoria-metrics-agent
    version: 0.21.0
    repository: https://victoriametrics.github.io/helm-charts/
  - name: victoria-metrics-single
    version: 0.20.0
    repository: https://victoriametrics.github.io/helm-charts/
  # Tracing
  - name: opentelemetry-collector
    version: 0.125.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: tempo
    version: 1.21.1
    repository: https://grafana.github.io/helm-charts
  # Profiling
  - name: pyroscope
    version: 1.13.4
    repository: https://grafana.github.io/helm-charts
  # Monitoring
  - name: grafana
    version: 9.1.1
    repository: https://grafana.github.io/helm-charts