spring:
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9093
server:
  port: 8080

logging:
  level:
    ROOT: DEBUG
    com.iz: DEBUG

server-name: localhost
database-port: 5432
database-name: objects
database-user: admin
database-password: password

events-url: http://localhost:8082
