spring:
  application:
    name: object-service
  datasource:
    url: jdbc:postgresql://${server-name:localhost}:${database-port:5432}/${database-name:objects}
    username: ${database-user:admin}
    password: ${database-password:password}
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: false
    database: postgresql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  jackson:
    default-property-inclusion: non_null
  liquibase:
    change-log: changelog.yml
  kafka:
    bootstrap-servers: kafka:9092
  cloud:
    #disabling ribbon
    loadbalancer:
      ribbon:
        enable: false

feign:
  httpclient:
    enabled: true
  client:
    config:
      events:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    ROOT: INFO
    com.iz: INFO

management.endpoints.web.exposure.include: '*'

topics:
  events: object.events

clients:
  events: http://localhost:8082/
