spring:
  application:
    name: object-service
  datasource:
    url: jdbc:postgresql://${server-name:localhost}:${database-port:5432}/${database-name:objects}
    username: ${database-user:admin}
    password: ${database-password:password}
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  jackson:
    default-property-inclusion: non_null
  liquibase:
    change-log: changelog.yml
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    #disabling ribbon
    loadbalancer:
      ribbon:
        enable: false
    compatibility-verifier:
      enabled: false # TODO enable after versions are compatible

  httpclient:
    enabled: true
  client:
    config:
      events:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

springdoc:
  api-docs:
    enabled: true
  show-actuator: false
  cache:
    disabled: true
  swagger-ui:
    csrf:
      enabled: true
    use-root-path: true
    urls:
      - name: Rest API
        url: /api/rest/objects-api.yaml
logging:
  level:
    ROOT: INFO
    com.iz: DEBUG
  pattern:
    level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} level=%p


management.endpoints.web.exposure.include: '*'

topics:
  events: object.events

clients:
  events: ${events-url:http://localhost:8082/}

validation:
  definitions:
    - type: bean
      name: decimalFieldValidation
      className: com.iz.sandbox.service.validation.impl.DecimalValueValidator
      order: 3
    - type: groovy
      name: intFieldValidation2
      path: validation/scripts/intFieldValidation2.groovy
      order: 4
