spring:
  application:
    name: object-service
  datasource:
    url: jdbc:postgresql://${server-name:localhost}:${database-port:5432}/${database-name:objects}
    username: ${database-user:admin}
    password: ${database-password:password}
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  jackson:
    default-property-inclusion: non_null
  liquibase:
    change-log: changelog.yml
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        # https://docs.confluent.io/platform/current/schema-registry/serdes-develop/serdes-json.html#json-schema-serializer-and-deserializer
        auto.register.schemas: true
        use.latest.version: true # not used with auto register enabled
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy

          # json config
          # https://github.com/confluentinc/schema-registry/blob/master/schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDeConfig.java
          # https://github.com/confluentinc/schema-registry/blob/master/json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaSerializerConfig.java
          #json:
        #schema.spec.version: draft_2019_09
        #write.dates.iso8601: true
        #fail.invalid.schema: true
    properties:
      schema.registry.url: ${schemaregistry.url}
  cloud:
    #disabling ribbon
    loadbalancer:
      ribbon:
        enable: false
    compatibility-verifier:
      enabled: false # TODO enable after versions are compatible
    schemaRegistryClient:
      endpoint: ${schemaregistry.url}

  httpclient:
    enabled: true
  client:
    config:
      events:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

springdoc:
  api-docs:
    enabled: true
  show-actuator: false
  cache:
    disabled: true
  swagger-ui:
    csrf:
      enabled: true
    use-root-path: true
    urls:
      - name: Rest API
        url: /objects-api.yaml
logging:
  level:
    ROOT: INFO
    com.iz: DEBUG
  pattern:
    level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} level=%p


management.endpoints.web.exposure.include: '*'

topics:
  events: object.events

clients:
  events: ${events-url:http://localhost:8082/}

validation:
  definitions:
    - type: bean
      name: decimalFieldValidation
      className: com.iz.sandbox.service.validation.impl.DecimalValueValidator
      order: 3
    - type: groovy
      name: intFieldValidation2
      path: validation/scripts/intFieldValidation2.groovy
      order: 4
