version: "3.9"
services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - '9100:9100'
    networks:
      default:
        aliases:
          - node_exporter
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      # scraper configuration
      - ./config/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      # file system
      - prometheus-data:/prometheus
    networks:
      default:
        aliases:
          - prometheus
  grafana:
    image: grafana/grafana:5.4.5
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=true
    ports:
      - '3000:3000'
    volumes:
      # file system
      - grafana-data:/var/lib/grafana
      # provisioning
      - ./config/monitoring/provisioning:/etc/grafana/provisioning
    networks:
      default:
        aliases:
          - grafana
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
networks:
  default:
      name: sandbox_default