version: "3.9"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.34
    ports:
      - '16686:16686'
      - '14250:14250'
      - '9411:9411'
    environment:
      - SPAN_STORAGE_TYPE=memory
  otel-collector:
    image: otel/opentelemetry-collector:0.63.1
    command: [ "--config=/conf/collector-config.yaml"]
    volumes:
      - ./config/tracing/otel-collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "4317:4317"
      - "9464:9464"
    depends_on:
      - jaeger


networks:
  default:
      name: sandbox_default