version: "3.9"
services:
  object-service:
    container_name: object-service
    image: object-service
    ports:
      - '8080:8080'
    environment:
      - spring.kafka.bootstrap-servers=kafka:9092
      - server-name=postgres
      - database-port=5432
      - database-name=objects
      - database-user=admin
      - database-password=password
      - events-url=http://object-events:8080
      - keycloak.url=http://keycloak-proxy:8888
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=object-service
      - OTEL_METRICS_EXPORTER=prometheus
      - OTEL_LOGS_EXPORTER=otlp
    networks:
      default:
        aliases:
          - object-service
  object-events:
    container_name: object-events
    image: object-events
    ports:
      - '8082:8080'
    environment:
      - spring.kafka.bootstrap-servers=kafka:9092
      - server-name=mongo
      - database-port=27017
      - auth-database-name=admin
      - database-name=local
      - database-user=admin
      - database-password=password
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=object-events
      - OTEL_METRICS_EXPORTER=prometheus
      - OTEL_LOGS_EXPORTER=otlp
    networks:
      default:
        aliases:
          - object-events
networks:
  default:
      name: sandbox_default