version: "3.9"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.34
    ports:
      - '16686:16686'
      - '14250:14250'
      - '9411:9411'
    environment:
      - SPAN_STORAGE_TYPE=memory
networks:
  default:
      name: sandbox_default