spring:
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9093

server:
  port: 8082

logging:
  level:
    ROOT: INFO
    com.iz: DEBUG

server-name: localhost
database-port: 27017
auth-database-name: admin
database-name: local
database-user: admin
database-password: password
