spring:
  application:
    name: object-service
  data:
    mongodb:
      database: ${database-name:local}
      host: ${server-name:localhost}
      port: ${database-port:27017}
      username: ${database-user:admin}
      password: ${database-password:password}
      authentication-database: ${auth-database-name:admin}
  jackson:
    default-property-inclusion: non_null
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      enable-auto-commit: false
      group-id: object-events
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        spring.json.key.default.type: java.lang.String
        spring.json.trusted.packages: '*'
        request.timeout.ms: '60000'
        session.timeout.ms: '180000'
        # https://docs.confluent.io/platform/current/schema-registry/serdes-develop/serdes-json.html#json-schema-serializer-and-deserializer
        auto.register.schemas: false
        use.latest.version: true
        # avro config
        specific.avro.reader: true

        # json config
        # https://github.com/confluentinc/schema-registry/blob/master/json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaDeserializerConfig.java
        # https://github.com/confluentinc/schema-registry/blob/master/schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDeConfig.java
        #json:
          #value.type: com.fasterxml.jackson.databind.JsonNode
          #schema.spec.version:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    listener:
      concurrency: 1
    properties:
      schema.registry.url: ${schemaregistry.url}


logging:
  level:
    ROOT: INFO
    com.iz: INFO

management.endpoints.web.exposure.include: '*'

topics:
  events: object.events
