receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
      insecure_skip_verify: true
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
    headers:
      x-scope-orgid: "Organization 1"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, otlp/jaeger]
      processors: [batch]
  telemetry:
    logs:
      level: "debug"