receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-metrics'
          scrape_interval: 5s
          static_configs:
            - targets:
              - 'object-service:9464'
              - 'object-events:9464'
        - job_name: "actuator-metrics"
          scrape_interval: 5s
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets:
                - 'object-service:8080'
                - 'object-events:8080'
exporters:
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
      insecure_skip_verify: true
  prometheus:
    endpoint: "0.0.0.0:9464"
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
    headers:
      x-scope-orgid: "Organization 1"
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tls:
      insecure: true
    labels:
      # mapping OTLP resource attributes to Loki labels
      resource:
        service.name: "service_name"
        host.name: "host_name"
    format: "body"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger, otlp]
      processors: [batch]
    metrics:
      receivers: [prometheus]
      exporters: [prometheus]
      processors: [batch]
    logs:
      receivers: [otlp]
      exporters: [loki]
      processors: [batch]
  telemetry:
    logs:
      level: "debug"