apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-service-account

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      serviceAccountName: mongo-service-account
      containers:
        - image: 'mongo:5.0.8'
          name: mongo
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongo-secrets
          resources: { }
          volumeMounts:
            - mountPath: /data/db
              name: mongo-claim0
      restartPolicy: Always
      volumes:
        - name: mongo-claim0
          persistentVolumeClaim:
            claimName: mongo-claim0
---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: password
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  ports:
    - name: "27017"
      port: 27017
  selector:
    app: mongo
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-express
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      serviceAccountName: mongo-service-account
      containers:
        - image: 'mongo-express:0.54.0'
          name: mongo-express
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: mongo-express-secrets
          resources: { }
      restartPolicy: Always

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secrets
type: Opaque
stringData:
  ME_CONFIG_MONGODB_ADMINUSERNAME: 'admin'
  ME_CONFIG_MONGODB_ADMINPASSWORD: 'password'
  ME_CONFIG_MONGODB_URL: 'mongodb://admin:password@mongo:27017/'

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-express
  name: mongo-express
spec:
  ports:
    - name: "8081"
      port: 8081
  selector:
    app: mongo-express
  type: LoadBalancer
      


