apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-claim0
  name: kafka-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zookeeper-claim0
  name: zookeeper-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: schema-registry-claim0
  name: schema-registry-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

