apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: keycloak-postgres-claim0
  name: keycloak-postgres-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

