global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: "node"
    scrape_interval: 1m
    static_configs:
      - targets: [ "node-exporter:9100" ]

  - job_name: "otel-collector"
    scrape_interval: 30s
    static_configs:
      - targets: [ "otel-collector:9464" ]

    # Transforming otel labels for prometheus/grafana needs
    metric_relabel_configs:
      - source_labels: ['exported_instance']
        target_label: "application"
        regex: '(.*):(.*)'
        replacement: "${1}"
      - source_labels: ['exported_instance']
        target_label: "app_instance"