global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: "node"
    scrape_interval: 1m
    static_configs:
      - targets: [ "node-exporter:9100" ]

  - job_name: "services"
    scrape_interval: 30s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "object-events:8080" ]
        labels:
          application: "object-events"
      - targets: [ "object-service:8080" ]
        labels:
          application: "object-service"