global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: "node"
    scrape_interval: 1m
    static_configs:
      - targets: [ "node-exporter:9100" ]

  - job_name: 'otel-metrics'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'object-service:9464'
          - 'object-events:9464'
    # Transforming otel labels for prometheus/grafana needs
    metric_relabel_configs:
      - source_labels: [ 'instance' ]
        target_label: "application"
        regex: '(.*):(.*)'
        replacement: "${1}"
      - source_labels: [ 'instance' ]
        target_label: "app_instance"

  - job_name: "actuator-metrics"
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'object-service:8080'
          - 'object-events:8080'

    # Transforming otel labels for prometheus/grafana needs
    metric_relabel_configs:
      - source_labels: ['instance']
        target_label: "application"
        regex: '(.*):(.*)'
        replacement: "${1}"
      - source_labels: ['instance']
        target_label: "app_instance"