[sources.in]
  type = "docker_logs"
  include_containers = [ "object-service", "object-events" ]
  
[sinks.out]
  # General
  type = "loki" # required
  inputs = ["in"] # required
  endpoint = "http://loki:3100" # required
  encoding.codec = "json"

  # Labels
  labels.container_name = "{{ container_name }}" # example