{{- if .Values.configMap.create -}}
  {{- if .Values.configMap.data -}}
# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.configMapName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap.data }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end -}}
  {{- end -}}
