
{{- if .Values.secret.create -}}
  {{- if .Values.secret.stringData -}}
# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.secretName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
  # Use stringData for automatic base64 encoding by Kubernetes
stringData:
  {{- range $key, $value := .Values.secret.stringData }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end -}}
  {{- end -}}
