apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: vector-agent-config
    files:
      - vector-agent.toml

namespace: default

resources:
  - pvc.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - daemonset.yaml

generatorOptions:
  disableNameSuffixHash: true