[sources.kubernetes]
    type = "kubernetes_logs"

[sinks.loki]
    # General
    type = "loki" # required
    inputs = ["kubernetes"] # required
    endpoint = "http://loki:3100" # required
    encoding.codec = "json"

# Labels
[sinks.loki.labels]
    file = "{{ file }}"
    stream = "{{ stream }}"
    source_type = "{{ source_type }}"
    pod_namespace = "{{ kubernetes.pod_namespace }}"
    pod_name = "{{ kubernetes.pod_name }}"
    pod_uid = "{{ kubernetes.pod_uid }}"
    service_name = "{{ kubernetes.pod_labels.app }}"
    container_name = "{{ kubernetes.container_name }}"