@startuml
autonumber

participant "Invoker" as invoker
participant "Object Service" as objectService #LightBlue
participant "Object Events Service" as objectEvents #LightBlue

invoker -> objectService: Object modification request \n [HTTP POST /objects] \n [HTTP PUT\DELETE /objects/{objectId}]
activate invoker
activate objectService
objectService -> objectService: Validate request

alt "Request is valid"
    objectService -> objectService: Persist object modifications
    objectService ->> objectEvents: Publish object modification event\n [kafka:object.events]
    activate objectEvents
    objectService --> invoker: Success response
    objectEvents -> objectEvents: Persist object modification event
    deactivate objectEvents
else "Request is not valid"
    objectService --> invoker: Error response
end
deactivate objectService
deactivate invoker

legend right
    |Color| Type |
    |<#LightBlue>| In context|
    |<#Business>| Not in context|
endlegend


@enduml