{
 "title": "Java Errors Corellation",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes, kubernetes_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{kubernetes_namespace=~\"$namespace\"}, kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{level=\"ERROR\", namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Log Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "irate(logback_events_total{level=\"error\", kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\",source=\"actuator\"}[$__rate_interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "REST Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{exception!=\"None\", uri!~\".*actuator.*\", kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", source=\"actuator\"}[$__rate_interval])) by (kubernetes_pod_name, exception)",
     "legendFormat": "{{kubernetes_pod_name}} - {{exception}}"
    }
   ]
  },
  {
   "title": "Request count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{uri!~\".*actuator.*\", kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", source=\"actuator\"}[$__rate_interval])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Kafka records consumed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(irate(kafka_consumer_records_consumed_total_total{kubernetes_pod_name=~\"$pod\", kubernetes_namespace=\"$namespace\", source=\"otel\"}[$__rate_interval])) by (kubernetes_pod_name, topic)",
     "legendFormat": "{{kubernetes_pod_name}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Lag",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(kafka_consumer_records_lag{kubernetes_pod_name=~\"$pod\", kubernetes_namespace=\"$namespace\", source=\"otel\"}) by (kubernetes_pod_name, topic)",
     "legendFormat": "{{kubernetes_pod_name}} - {{topic}}"
    }
   ]
  }
 ]
}