{
 "title": "K8s Resource Monitoring",
 "description": "The dashboard offers a simple view of the resource consumption of the deployed pods and their impact on the cluster. The outline of requests and limits for each pod and their totals can be used as a tool to determine appropriate resource quotas for your cluster.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(container_memory_working_set_bytes,cluster)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max (100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{cluster=\"$cluster\"}[$__rate_interval]) + avg_over_time(node_memory_Cached_bytes{cluster=\"$cluster\"}[$__rate_interval]) + avg_over_time(node_memory_Buffers_bytes{cluster=\"$cluster\"}[$__rate_interval])) / avg_over_time(node_memory_MemTotal_bytes{cluster=\"$cluster\"}[$__rate_interval])))) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (avg_over_time(node_memory_MemFree_bytes{cluster=\"$cluster\"}[$__rate_interval]) + avg_over_time(node_memory_Cached_bytes{cluster=\"$cluster\"}[$__rate_interval]) + avg_over_time(node_memory_Buffers_bytes{cluster=\"$cluster\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "min(node_filesystem_avail_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\", device!=\"overlay\", cluster=\"$cluster\"}/node_filesystem_size_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\", device!=\"overlay\", cluster=\"$cluster\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{cluster=\"$cluster\"}[10m]) + avg_over_time(node_memory_Cached_bytes{cluster=\"$cluster\"}[10m]) + avg_over_time(node_memory_Buffers_bytes{cluster=\"$cluster\"}[10m])) / avg_over_time(node_memory_MemTotal_bytes{cluster=\"$cluster\"}[10m])))) by (node)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(1 - rate(node_cpu_seconds_total{mode=\"idle\", cluster=\"$cluster\"}[2m])) by (node)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Pods Restarted",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (pod)(delta(kube_pod_container_status_restarts_total{cluster=\"$cluster\"}[15m]) > 0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Running Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{cluster=\"$cluster\"}) by (phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "kubelet_running_pod_count{kubernetes_io_role =~ \".*node.*\", cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Top 5 Memory Intense Pods",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5,sum(container_memory_working_set_bytes{pod!=\"\", cluster=\"$cluster\"}) by (pod))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\"}) by (pod)"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\"}) by (pod)"
    },
    {
     "expr": "max(container_memory_working_set_bytes{cluster=\"$cluster\", pod!=\"\"}) by (pod)"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{resource=\"cpu\", cluster=\"$cluster\"}) by (pod)"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod!=\"\", cluster=\"$cluster\"}[5m])) by (pod)"
    },
    {
     "expr": "max(kube_pod_info{cluster=\"$cluster\"}) by (pod,namespace,node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total pod memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod!=\"\", cluster=\"$cluster\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU usage (mcores)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod!=\"\", cluster=\"$cluster\"}[5m]) * 1000) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}