{
 "title": "Spring Boot HikariCP / JDBC",
 "description": "HikariCP & JDBC Dashboard (Micrometer.io)",
 "tags": [
  "prometheus",
  "hikaricp",
  "micrometer",
  "spring boot",
  "jdbc"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(jdbc_connections_min, application)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jdbc_connections_min{application=~\"$application\"}, kubernetes_namespace)"
    }
   },
   {
    "name": "instance",
    "label": "Pod",
    "query": {
     "query": "label_values(jdbc_connections_min{application=~\"$application\", kubernetes_namespace=~\"$namespace\", job=\"kubernetes-pods-actuator\"}, kubernetes_pod_name)"
    }
   },
   {
    "name": "jdbc_connection_name",
    "label": "JDBC Connection Name",
    "query": {
     "query": "label_values(jdbc_connections_min{application=~\"$application\", kubernetes_namespace=~\"$namespace\", job=\"kubernetes-pods-actuator\", kubernetes_pod_name=~\"$instance\"}, name)"
    }
   },
   {
    "name": "hikaricp_pool_name",
    "label": "Hikari  Pool Name",
    "query": {
     "query": "label_values(hikaricp_connections_min{application=~\"$application\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$instance\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Hikari Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active{application=~\"$application\", job=\"kubernetes-pods-actuator\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$instance\", pool=~\"$hikaricp_pool_name\"})",
     "legendFormat": "Active connections"
    },
    {
     "expr": "sum (hikaricp_connections_idle{application=~\"$application\", job=\"kubernetes-pods-actuator\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$instance\", pool=~\"$hikaricp_pool_name\"})",
     "legendFormat": "Idle connections"
    },
    {
     "expr": "sum(hikaricp_connections_pending{application=~\"$application\", job=\"kubernetes-pods-actuator\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$instance\", pool=~\"$hikaricp_pool_name\"})",
     "legendFormat": "Pending threads"
    },
    {
     "expr": "sum(hikaricp_connections_min{application=~\"$application\", kubernetes_namespace=~\"$namespace\", job=\"kubernetes-pods-actuator\", kubernetes_pod_name=~\"$instance\", pool=~\"$hikaricp_pool_name\"})",
     "legendFormat": "Min connections"
    },
    {
     "expr": "sum(hikaricp_connections_max{application=~\"$application\", kubernetes_namespace=~\"$namespace\", job=\"kubernetes-pods-actuator\", kubernetes_pod_name=~\"$instance\", pool=~\"$hikaricp_pool_name\"})",
     "legendFormat": "Max connections"
    }
   ]
  },
  {
   "title": "Connections Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "irate(hikaricp_connections_usage_seconds_sum{application=~\"$application\", job=\"kubernetes-pods-actuator\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m]) / irate(hikaricp_connections_usage_seconds_count{application=\"$application\", job=\"kubernetes-pods-actuator\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m])",
     "legendFormat": "Usage time"
    },
    {
     "expr": "irate(hikaricp_connections_creation_seconds_sum{application=~\"$application\", job=\"kubernetes-pods-actuator\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m]) / irate(hikaricp_connections_creation_seconds_count{application=\"$application\", job=\"kubernetes-pods-actuator\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m])",
     "legendFormat": "Creation time"
    },
    {
     "expr": "irate(hikaricp_connections_acquire_seconds_sum{application=~\"$application\", job=\"kubernetes-pods-actuator\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m]) / irate(hikaricp_connections_acquire_seconds_count{application=\"$application\", job=\"kubernetes-pods-actuator\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m])",
     "legendFormat": "Acquire time"
    }
   ]
  },
  {
   "title": "Connection Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_timeout_total{application=~\"$application\", job=\"kubernetes-pods-actuator\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$instance\", pool=~\"$hikaricp_pool_name\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "JDBC Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JDBC Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(jdbc_connections_min{application=~\"$application\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$instance\", job=\"kubernetes-pods-actuator\", name=~\"$jdbc_connection_name\"})",
     "legendFormat": "Min connections"
    },
    {
     "expr": "sum(jdbc_connections_max{application=~\"$application\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$instance\", job=\"kubernetes-pods-actuator\", name=~\"$jdbc_connection_name\"})",
     "legendFormat": "Max connections"
    }
   ]
  }
 ]
}